fix(auth) fix auth tests

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -78,14 +78,21 @@ test_autorization:
     - TEST_EMAIL="me.test@example.com"
     - TEST_PASSWORD="123"
     - >
-      docker run --rm --network "$NETWORK" curlimages/curl:8.11.0 -s -X POST
+      REGISTER_RESPONSE=$(docker run --rm --network "$NETWORK" curlimages/curl:8.11.0 -s -X POST
       -H "Content-Type: application/json"
-      -d "{\"email\":\"$TEST_EMAIL\",\"password\":\"$TEST_PASSWORD\"}"
-      http://gateway:8080/register
+      -d '{"email":"$TEST_EMAIL","password":"$TEST_PASSWORD"}'
+      http://gateway:8080/register)
+    - echo "Register response $REGISTER_RESPONSE"
+    - if [ "$REGISTER_RESPONSE" -ne "201" ]; then
+          echo "FAIL':' register /register expected 201, got $REGISTER_RESPONSE"
+          docker compose --env-file .env -f backend/deployment/docker/docker-compose.yml logs gateway
+          exit 1
+        fi
+        echo "PASS':' register /register returned 201 as expected"
     - >
       LOGIN_RESPONSE=$(docker run --rm --network "$NETWORK" curlimages/curl:8.11.0 -s -X POST
       -H "Content-Type: application/json"
-      -d "{\"email\":\"$TEST_EMAIL\",\"password\":\"$TEST_PASSWORD\"}"
+      -d '{"email":"$TEST_EMAIL","password":"$TEST_PASSWORD"}'
       http://gateway:8080/login)
     - echo "Login response $LOGIN_RESPONSE"
     - TOKEN=$(echo "$LOGIN_RESPONSE" | grep -o '"token":"[^"]*' | sed 's/"token":"//')
